package proyectomeia;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyectomeia.Clases.Singleton;
import proyectomeia.Clases.Usuario;
import proyectomeia.Clases.bitacoraBackUp;

public class MenuCambios extends javax.swing.JFrame {

    private String seleccion;
    private String rol;
    private String nuevaRuta = "";
    private String nuevaRuta_ = "";
    private static int registros = 0;

    public MenuCambios() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        imgFoto.setEnabled(false);
        txtPassword.setEnabled(false);
        txtCorreoAlterno.setEnabled(false);
        dateFechaNacimiento.setEnabled(false);
        txtTelefono.setEnabled(false);
        chkActivarDesactivar.setEnabled(false);
        jCheckBox2.setEnabled(false);

    }

    public MenuCambios(Singleton datos) {
        this();
        fase = datos;
        if (datos.current.isRol() == false) {
            TabsMenu.setEnabledAt(1, false);
        } else {
            jCheckBox1.setVisible(false);
        }
        modifica = new Usuario();
        btnGuardar.setEnabled(false);
        btnHabilitarEdicion.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        btnGuardarCusuario.setEnabled(false);
        jLabel12.setText(fase.current.getCorreo_alterno());
        jLabel13.setText(fase.current.getFecha_nacimiento());
        jLabel14.setText(String.valueOf(fase.current.getTelefono()));
        jLabel15.setIcon(new ImageIcon(new ImageIcon(fase.current.getPath_fotografía()).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    fase.Usuarios.refactorBitacora();
                    fase.ListaUsuarios.EliminacionLogicaAlCerrar(fase.current.getUsername().trim());
                } catch (IOException ex) {
                    Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }
    private Singleton fase;
    private Usuario modifica;
    private String password = "";
    private String correo = "";
    private String fecha = "";
    private String telefono = "";
    private String password_ = "";
    private String correo_ = "";
    private String fecha_ = "";
    private String telefono_ = "";
    private String status = "";
    private String rutaBackUp = Paths.get("C:/MEIA_BackUp/").toString();
    ;;
    private String rutaMEIA = Paths.get("C:/MEIA/").toString();
    private String rutabitacora = Paths.get("C:/MEIA/bitacora_backup.txt").toString();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        TabsMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtNpass = new javax.swing.JLabel();
        fieldNpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        fieldCNpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnreg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtN_email = new javax.swing.JLabel();
        fieldN_email = new javax.swing.JTextField();
        buttonN_email = new javax.swing.JButton();
        txtNdate = new javax.swing.JLabel();
        txtNphone = new javax.swing.JLabel();
        fieldNphone = new javax.swing.JTextField();
        buttonN_date = new javax.swing.JButton();
        txtNpic = new javax.swing.JLabel();
        buttonNphone = new javax.swing.JButton();
        buttonNpic = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnGuardarCusuario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkActivarDesactivar = new javax.swing.JCheckBox();
        btnHabilitarEdicion = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtCorreoAlterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarUsuario = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        imgFoto = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnClista = new javax.swing.JButton();
        dateFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de cambios");
        setLocation(new java.awt.Point(300, 200));

        TabsMenu.setBackground(new java.awt.Color(102, 102, 102));
        TabsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        txtNpass.setText("Ingrese contraseña anterior");

        jLabel1.setText("Ingrese nueva contraseña");

        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnreg.setText("Regresar");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldNpass)
                    .addComponent(jLabel1)
                    .addComponent(fieldCNpass))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(358, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreg)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(txtNpass)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldNpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldCNpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)))
                    .addComponent(btnreg))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cambiar Contraseña", jPanel4);

        txtN_email.setText("Ingrese nuevo correo");

        buttonN_email.setText("Cambiar");
        buttonN_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonN_emailActionPerformed(evt);
            }
        });

        txtNdate.setText("Nueva fecha de nacimiento");

        txtNphone.setText("Nuevo teléfono");

        buttonN_date.setText("Cambiar");
        buttonN_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonN_dateActionPerformed(evt);
            }
        });

        txtNpic.setText("Nueva fotografía");

        buttonNphone.setText("Cambiar");
        buttonNphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNphoneActionPerformed(evt);
            }
        });

        buttonNpic.setText("Cambiar");
        buttonNpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNpicActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Darse de Baja");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btnGuardarCusuario.setText("Guardar");
        btnGuardarCusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCusuarioActionPerformed(evt);
            }
        });

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fieldN_email, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtN_email))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(buttonNphone))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fieldNphone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonN_email)
                            .addComponent(txtNphone))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNdate)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNpic)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(buttonN_date)
                                                .addGap(36, 36, 36)
                                                .addComponent(jCheckBox1))
                                            .addComponent(buttonNpic))))
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnGuardarCusuario)
                                .addGap(123, 123, 123))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addGap(115, 115, 115)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonN_date, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtN_email)
                            .addComponent(txtNdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldN_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonN_email)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtNpic)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNphone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNphone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(buttonNpic)
                .addGap(83, 83, 83))
        );

        jTabbedPane2.addTab("Cambiar Datos", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        TabsMenu.addTab("Opciones de Usuario", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Foto:");

        jLabel4.setText("Password: ");

        jLabel5.setText("Correo Alterno:");

        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setText("Telefono:");

        chkActivarDesactivar.setText("Activar/Desactivar");

        btnHabilitarEdicion.setText("Habilitar Edicion");
        btnHabilitarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarEdicionActionPerformed(evt);
            }
        });

        btnCrearUsuario.setText("Crear Nuevo Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar Usuario:");

        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        imgFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFotoMouseClicked(evt);
            }
        });

        jCheckBox2.setText("Administrador");

        jLabel2.setText("jLabel2");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jButton2.setText("cambiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("cambiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("cambiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("cambiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnBackup.setText("Backup");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnClista.setText("Crear Lista");
        btnClista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHabilitarEdicion)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackup)
                .addGap(8, 8, 8))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreoAlterno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(131, 131, 131))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(404, 404, 404))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(chkActivarDesactivar)
                                .addGap(40, 40, 40)
                                .addComponent(jCheckBox2)
                                .addGap(48, 48, 48)
                                .addComponent(btnGuardar))
                            .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel11)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabilitarEdicion)
                    .addComponent(btnCrearUsuario)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarUsuario))
                    .addComponent(btnClista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreoAlterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton4)
                    .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkActivarDesactivar)
                    .addComponent(btnGuardar)
                    .addComponent(jCheckBox2))
                .addContainerGap())
        );

        TabsMenu.addTab("Opciones de Administrador", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonN_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonN_dateActionPerformed
        fecha_ = dateFechaNacimiento.getText();
        if (!fecha_.isEmpty()) {
            if (fase.current.getFecha_nacimiento().contains(fecha_)) {
                JOptionPane.showMessageDialog(null, "No se modifico la fecha de nacimiento del usuario");
                fecha_ = "";
            } else {
                if (!btnGuardarCusuario.isEnabled()) {
                    btnGuardarCusuario.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_buttonN_dateActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        CreateUser nuevoUsuario = new CreateUser(fase, 2);
        nuevoUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnHabilitarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarEdicionActionPerformed

        imgFoto.setEnabled(true);
        txtPassword.setEnabled(true);
        txtCorreoAlterno.setEnabled(true);
        dateFechaNacimiento.setEnabled(true);
        txtTelefono.setEnabled(true);
        chkActivarDesactivar.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
    }//GEN-LAST:event_btnHabilitarEdicionActionPerformed


    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed

        try {
            List<String> found = fase.Usuarios.bitacora.Busqueda(txtBuscarUsuario.getText());
            if (found.isEmpty()) {
                String encontrado_ = fase.Usuarios.Buscar(txtBuscarUsuario.getText());
                modifica.CreatefromString(encontrado_);
                if (!modifica.isRol()) {
                    imgFoto.setIcon(new ImageIcon(new ImageIcon(modifica.getPath_fotografía()).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
                    jLabel2.setText(modifica.getPassword());
                    jLabel9.setText(modifica.getCorreo_alterno());
                    jLabel10.setText(modifica.getFecha_nacimiento());
                    jLabel11.setText(String.valueOf(modifica.getTelefono()));
                    if (modifica.isRol()) {
                        chkActivarDesactivar.setSelected(false);
                    } else {
                        chkActivarDesactivar.setSelected(true);
                    }
                    JOptionPane.showMessageDialog(null, "usuario:" + modifica.getUsername() + " " + "encontrado");
                    btnHabilitarEdicion.setEnabled(true);
                    btnBuscarUsuario.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "usuario:" + modifica.getUsername() + " " + "encontrado, no modificable");
                }

            } else {
                String line = "";
                for (int i = 0; i < found.size(); i++) {
                    line = found.get(i);
                    if (!line.contains("/0")) {
                        line = line;
                    } else {
                        line = "";
                    }

                }
                modifica.CreatefromString(line);
                if (modifica.isRol()) {
                    imgFoto.setIcon(new ImageIcon(new ImageIcon(modifica.getPath_fotografía()).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
                    jLabel2.setText(modifica.getPassword());
                    jLabel9.setText(modifica.getCorreo_alterno());
                    jLabel10.setText(modifica.getFecha_nacimiento());
                    jLabel11.setText(String.valueOf(modifica.getTelefono()));
                    if (modifica.getStatus()) {
                        chkActivarDesactivar.setSelected(true);
                    } else {
                        chkActivarDesactivar.setSelected(false);
                    }
                    if (modifica.isRol()) {
                        jCheckBox2.setSelected(true);
                    } else {
                        jCheckBox2.setSelected(false);
                    }
                    JOptionPane.showMessageDialog(null, "usuario:" + modifica.getUsername() + " " + "encontrado");
                    btnHabilitarEdicion.setEnabled(true);
                    btnBuscarUsuario.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "usuario:" + modifica.getUsername() + " " + "encontrado, no modificable");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al obtener datos");
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (chkActivarDesactivar.isSelected()) {
            seleccion = "1";
        } else {
            seleccion = "0";
        }
        if (jCheckBox2.isSelected()) {
            rol = "1";
        } else {
            rol = "0";
        }
        if (password.isEmpty()) {
            password = modifica.getPassword();
        }
        if (correo.isEmpty()) {
            correo = modifica.getCorreo_alterno();
        }
        if (fecha.isEmpty()) {
            fecha = modifica.getFecha_nacimiento();
        }
        if (telefono.isEmpty()) {
            telefono = String.valueOf(modifica.getTelefono());
        }
        if (nuevaRuta.isEmpty()) {
            nuevaRuta = modifica.getPath_fotografía();
        }
        Usuario newUser = new Usuario();
        newUser.setUsername(modifica.getUsername());
        newUser.setNombre(modifica.getNombre());
        newUser.setApellido(modifica.getApellido());
        newUser.setPassword(password);
        newUser.setCorreo_alterno(correo);
        newUser.setFecha_nacimiento(fecha);
        newUser.setTelefono(Integer.parseInt(telefono));
        newUser.setPath_fotografía(nuevaRuta);
        newUser.setRol(rol.equals("1"));
        newUser.setStatus(seleccion.equals("1"));
        try {
            fase.Usuarios.Modificar(newUser.toString(), modifica.toString());
            imgFoto.setEnabled(false);
            txtPassword.setEnabled(false);
            txtCorreoAlterno.setEnabled(false);
            dateFechaNacimiento.setEnabled(false);
            txtTelefono.setEnabled(false);
            chkActivarDesactivar.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jCheckBox2.setEnabled(false);
            btnHabilitarEdicion.setEnabled(false);
            btnBuscarUsuario.setEnabled(true);
            btnGuardar.setEnabled(false);
            if (fase.Usuarios.flag == true) {
                fase.Usuarios.updateAutorMod(fase.current.getUsername());
            }
        } catch (IOException ex) {
            Logger.getLogger(MenuCambios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void imgFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFotoMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG", "jpeg", "jpg", "png");
        File imagen;

        chooser.setFileFilter(filter);
        int valor = chooser.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            imagen = chooser.getSelectedFile();
            nuevaRuta = imagen.getPath();
            if (modifica.getPath_fotografía().contains(nuevaRuta) || nuevaRuta.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se modifico la imagen del usuario");
                nuevaRuta = "";
            }
        }
    }//GEN-LAST:event_imgFotoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        password = txtPassword.getText();
        if (!password.isEmpty()) {
            if (modifica.getPassword().contains(password)) {
                JOptionPane.showMessageDialog(null, "No se modifico la contraseña del usuario");
                password = "";
            } else {
                if (!btnGuardar.isEnabled()) {
                    btnGuardar.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        correo = txtCorreoAlterno.getText();
        String regex = "^([_a-zA-Z0-9-]+(\\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{1,6}))?$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(correo);
        if (!correo.isEmpty()) {
            if (modifica.getCorreo_alterno().contains(correo) || !matcher.matches()) {
                JOptionPane.showMessageDialog(null, "No se modifico el correo del usuario");
                correo = "";
            } else {
                if (!btnGuardar.isEnabled()) {
                    btnGuardar.setEnabled(true);
                }
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fecha = dateFechaNacimiento.getText();
        if (!fecha.isEmpty()) {
            if (modifica.getFecha_nacimiento().contains(fecha)) {
                JOptionPane.showMessageDialog(null, "No se modifico la fecha de nacimiento del usuario");
                fecha = "";
            } else {
                if (!btnGuardar.isEnabled()) {
                    btnGuardar.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        telefono = txtTelefono.getText();
        if (!telefono.isEmpty()) {
            if (String.valueOf(modifica.getTelefono()).contains(telefono) || !onlyNumbers(telefono) || telefono.length() != 8) {
                JOptionPane.showMessageDialog(null, "No se modifico el telefono del usuario");
                telefono = "";
            } else {
                if (!btnGuardar.isEnabled()) {
                    btnGuardar.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buttonN_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonN_emailActionPerformed
        correo_ = fieldN_email.getText();
        String regex = "^([_a-zA-Z0-9-]+(\\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{1,6}))?$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(correo_);
        if (!correo_.isEmpty()) {
            if (fase.current.getCorreo_alterno().contains(correo_) || !matcher.matches()) {
                JOptionPane.showMessageDialog(null, "No se modifico el correo del usuario");
                correo_ = "";
            } else {
                if (!btnGuardarCusuario.isEnabled()) {
                    btnGuardarCusuario.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_buttonN_emailActionPerformed

    private void buttonNphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNphoneActionPerformed
        telefono_ = fieldNphone.getText();
        if (!telefono_.isEmpty()) {
            if (String.valueOf(fase.current.getTelefono()).contains(telefono_) || !onlyNumbers(telefono_) || telefono_.length() != 8) {
                JOptionPane.showMessageDialog(null, "No se modifico el telefono del usuario");
                telefono = "";
            } else {
                if (!btnGuardarCusuario.isEnabled()) {
                    btnGuardarCusuario.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_buttonNphoneActionPerformed

    private void buttonNpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNpicActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG", "jpeg", "jpg", "png");
        File imagen;

        chooser.setFileFilter(filter);
        int valor = chooser.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            imagen = chooser.getSelectedFile();
            nuevaRuta = imagen.getPath();
            if (fase.current.getPath_fotografía().contains(nuevaRuta_) || nuevaRuta_.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se modifico la imagen del usuario");
                nuevaRuta_ = "";
            }
        }
    }//GEN-LAST:event_buttonNpicActionPerformed

    private void btnGuardarCusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCusuarioActionPerformed

        if (jCheckBox1.isSelected()) {
            status = "0";
        } else {
            status = "1";
        }

        password_ = fase.current.getPassword();

        if (correo_.isEmpty()) {
            correo_ = fase.current.getCorreo_alterno();
        }
        if (fecha_.isEmpty()) {
            fecha_ = fase.current.getFecha_nacimiento();
        }
        if (telefono_.isEmpty()) {
            telefono_ = String.valueOf(fase.current.getTelefono());
        }
        if (nuevaRuta_.isEmpty()) {
            nuevaRuta_ = fase.current.getPath_fotografía();
        }
        Usuario newUser = new Usuario();
        newUser.setUsername(fase.current.getUsername());
        newUser.setNombre(fase.current.getNombre());
        newUser.setApellido(fase.current.getApellido());
        newUser.setPassword(password_);
        newUser.setCorreo_alterno(correo_);
        newUser.setFecha_nacimiento(fecha_);
        newUser.setTelefono(Integer.parseInt(telefono_));
        newUser.setPath_fotografía(nuevaRuta_);
        newUser.setRol(fase.current.isRol());
        newUser.setStatus(status.equals("1"));
        try {
            fase.Usuarios.Modificar(newUser.toString(), fase.current.toString());
            btnGuardarCusuario.setEnabled(false);
            fase.current = newUser;
            if (fase.Usuarios.flag == true) {
                fase.Usuarios.updateAutorMod(fase.current.getUsername());
            }
            if (fase.current.getStatus() == true) {
                UserView view = new UserView(fase);
                view.show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Se deshabilitó el usuario");
                fase.current = null;
                Inicio retorno = new Inicio(fase);
                retorno.show();
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(MenuCambios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarCusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        password_ = String.valueOf(fieldNpass.getPassword());
        if (!password_.isEmpty()) {
            if (fase.current.getPassword().contains(password_)) {
                if (StrongEnoughPass(fieldCNpass.getPassword())) {
                    JOptionPane.showMessageDialog(null, "Su nueva contraseña es segura");
                    String newpass = String.valueOf(fieldCNpass.getPassword());
                    Usuario newuser = fase.current;
                    newuser.setPassword(newpass);
                    try {
                        fase.Usuarios.Modificar(newuser.toString(), fase.current.toString());
                        if (fase.Usuarios.flag == true) {
                            fase.Usuarios.updateAutorMod(fase.current.getUsername());
                        }
                        JOptionPane.showMessageDialog(null, "Se cambio su contraseña, vuelva a iniciar sesión");
                        fase.current = null;
                        Inicio retorno = new Inicio(fase);
                        retorno.show();
                        this.dispose();

                    } catch (IOException ex) {
                        Logger.getLogger(MenuCambios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Su nueva contraseña no es segura");
                }
            } else {
                JOptionPane.showMessageDialog(null, "contraseña anterior incorrecta");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Escriba su contraseña anterior");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Guardar BackUp");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            rutaBackUp = chooser.getCurrentDirectory().toString();
            File original = new File(rutaMEIA);
            File backUp = new File(Paths.get(rutaBackUp + "/MEIA_BackUp/").toString());
            copiarDirectorio(original, backUp);
            bitacoraBackUp backup = new bitacoraBackUp(rutabitacora, fase.current.getUsername());
            try {
                backup.Insertar(backUp.getAbsolutePath(), fase.current.getUsername());
            } catch (IOException ex) {
                Logger.getLogger(MenuCambios.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "BackUp Realizado con exito en :" + backUp.getPath());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una ruta valida");
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnClistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClistaActionPerformed
        ListaAdmin crear = new ListaAdmin(fase);
        crear.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClistaActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        UserView view = new UserView(fase);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregActionPerformed
    private void copiarArchivos(File original, File destino) {
        try {
            InputStream entrada = new FileInputStream(original);

            OutputStream salida = new FileOutputStream(destino);
            byte[] buffer = new byte[1024];
            int datos;
            while ((datos = entrada.read(buffer)) > 0) {
                salida.write(buffer, 0, datos);
            }
            entrada.close();
            salida.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar el back up");
        }
    }

    private void copiarDirectorio(File original, File copia) {

        if (original.isDirectory()) {
            if (!copia.exists()) {
                copia.mkdir();
            }
            String[] archivos = original.list();
            for (int i = 0; i < archivos.length; i++) {
                copiarDirectorio(new File(original, archivos[i]), new File(copia, archivos[i]));
            }
        } else {
            copiarArchivos(original, copia);
        }
    }

    private boolean onlyNumbers(String cadena) {
        int c = 0;
        for (int i = 0; i < cadena.length(); i++) {
            if (Isnumber(String.valueOf(cadena.charAt(i)))) {
                c++;
            }
        }
        if (c == cadena.length()) {
            return true;
        } else {
            return false;
        }
    }

    private boolean Isnumber(String counter) {
        try {
            Integer.parseInt(counter);
        } catch (Exception e) {
            return false;

        }
        return true;
    }

    private boolean onlyLetters(String cadena) {
        int c = 0;
        for (int i = 0; i < cadena.length(); i++) {
            if (Character.isLetter(cadena.charAt(i)) == true) {
                c++;
            }
        }
        if (c == cadena.length()) {
            return true;
        } else {
            return false;
        }
    }

    private int SecurityCode(int puntuacion) {
        String[] resultado = new String[]{"0", "25", "26", "35", "36", "50", "51", "100"};

        if (puntuacion > Integer.parseInt(resultado[0]) && puntuacion <= Integer.valueOf(resultado[1])) {
            return 1;
        } else if (puntuacion > Integer.parseInt(resultado[2]) && puntuacion <= Integer.valueOf(resultado[3])) {
            return 2;
        } else if (puntuacion > Integer.parseInt(resultado[4]) && puntuacion <= Integer.valueOf(resultado[5])) {
            return 3;
        } else if (puntuacion > Integer.parseInt(resultado[6]) && puntuacion <= Integer.valueOf(resultado[7])) {
            return 4;
        } else {
            return 0;
        }
    }

    private boolean StrongEnoughPass(char[] password) {
        String pass = new String(password);
        int puntuacion;
        String especiales = "/¿?%$#";
        String[] puntuacionArray = new String[]{"3", "2", "1", "2", "4", "6", "3"};
        puntuacion = Integer.parseInt(puntuacionArray[0]) * pass.length();
        ArrayList<String> contadorMayus = new ArrayList<>();
        for (int i = 0; i < pass.length(); i++) {
            if ((Integer.valueOf(pass.charAt(i)) > 64) && (Integer.valueOf(pass.charAt(i)) < 91)) {
                contadorMayus.add(String.valueOf(pass.charAt(i)));
            }
        }
        puntuacion = puntuacion + (Integer.valueOf(puntuacionArray[1]) * contadorMayus.size());
        int counter = 0;
        for (int i = 0; i < pass.length(); i++) {
            if ((!especiales.contains(String.valueOf(pass.charAt(i)))) || Isnumber(String.valueOf(pass.charAt(i))) == false) {
                counter++;
            }

        }
        puntuacion = puntuacion + (counter + Integer.valueOf(puntuacionArray[2]));
        counter = 0;
        for (int i = 0; i < pass.length(); i++) {
            if (Isnumber(String.valueOf(pass.charAt(i)))) {
                counter++;
            }
        }
        puntuacion = puntuacion + (counter + Integer.valueOf(puntuacionArray[3]));
        counter = 0;
        for (int i = 0; i < pass.length(); i++) {
            if (especiales.contains(String.valueOf(pass.charAt(i)))) {
                counter++;
            }
        }
        puntuacion = puntuacion + counter * (pass.length() + Integer.parseInt(puntuacionArray[4]));
        if (counter == 0) {
            if (onlyNumbers(pass) == true) {
                puntuacion = puntuacion - Integer.parseInt(puntuacionArray[6]);
            } else if (onlyLetters(pass) == true) {
                puntuacion = puntuacion - Integer.parseInt(puntuacionArray[5]);
            }
        }
        int seguridad = SecurityCode(puntuacion);
        registros = seguridad;
        if (seguridad >= 3) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCambios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabsMenu;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnClista;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCusuario;
    private javax.swing.JButton btnHabilitarEdicion;
    private javax.swing.JButton btnreg;
    private javax.swing.JButton buttonN_date;
    private javax.swing.JButton buttonN_email;
    private javax.swing.JButton buttonNphone;
    private javax.swing.JButton buttonNpic;
    private javax.swing.JCheckBox chkActivarDesactivar;
    private com.github.lgooddatepicker.components.DatePicker dateFechaNacimiento;
    private javax.swing.JPasswordField fieldCNpass;
    private javax.swing.JTextField fieldN_email;
    private javax.swing.JPasswordField fieldNpass;
    private javax.swing.JTextField fieldNphone;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JTextField txtCorreoAlterno;
    private javax.swing.JLabel txtN_email;
    private javax.swing.JLabel txtNdate;
    private javax.swing.JLabel txtNpass;
    private javax.swing.JLabel txtNphone;
    private javax.swing.JLabel txtNpic;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}